[package]
name = "grnenv-rs"
version = "0.1.0"
authors = ["Hiroshi Hatake <cosmo0920.wp@gmail.com>"]

[lib]
name = "grnenvlib"
path = "src/lib.rs"

[dependencies]
tempdir = "~0.3"
hyper = "~0.9.10"
zip = "~0.1"
clap = "~2.13"
libc = "~0.2.15"
env_proxy = "~0.1"

[dependencies.kuchiki]
version = "~0.3.4"
features = ["hyper"]

[target.'cfg(windows)'.dependencies]
kernel32-sys = "~0.2"

[target.'cfg(not(windows))'.dependencies]
sys-info = "0.4.1"
